### ISSUE TITLE
Doesn't work in Safari

### ISSUE THREAD

**Issue by ibrent** [davidecalignano/MediumLightbox#1]
using Safari 8.0.4

Clicking on the image just blocks out a white rectangle around the image, which also doesn't enlarge.

![screen shot 2015-03-20 at 10 16 43 am](https://cloud.githubusercontent.com/assets/351251/6756898/41c6b03e-ceea-11e4-9c34-3bcfd6ea103a.png)
![screen shot 2015-03-20 at 10 16 23 am](https://cloud.githubusercontent.com/assets/351251/6756901/4628ab6e-ceea-11e4-8698-4a8437589643.png)

**Comment by emersonthis** [comment]
Same issue on Mobile Safari as well. iOS8.2

**Comment by emersonthis** [comment]
Just submitted a PR #3 which fixes this.
