### ISSUE TITLE
Double scroll bar

### ISSUE THREAD

**Issue by anabelLeva** [davidecalignano/MediumLightbox#5]
How do I remove/hide/disable the second scroll bar?

http://anabel.me/testing/portfolio/focus-process-book.html

**Comment by davidecalignano** [comment]
Hi Anabel, looking into your code, seem that the problem is related to
the margin-bottom property with -4px applied to .footer-banner, set the
value to 0px, and it should be fine.

**Comment by anabelLeva** [comment]
Perfect! Thank you!
