### ISSUE TITLE
Portrait to Landscape back to Portrait has some funky results/

### ISSUE THREAD

**Issue by simsketch** [davidecalignano/MediumLightbox#8]
![image](https://cloud.githubusercontent.com/assets/3129129/21653005/19ed93c8-d27d-11e6-9281-2b491c4a4e13.png)
Chrome browser iPhone 7 Plus

**Comment by davidecalignano** [comment]
From the screenshot seems like the page doesn't have the right viewport to display the content on mobile. Can you check it out?

**Comment by davidecalignano** [comment]
Closed due to inactivity.
